spring:
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jooq:
    sql-dialect: POSTGRES
    code-gen: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

etherscan:
  api:
    url: https://api.etherscan.io/api
    key: ${ETHERSCAN_API_KEY}

scheduler:
  shouldRunLatestFirst: ${SHOULD_PROCESS_LATEST_BLOCKS}
  parallelApiCalls: ${PARALLEL_API_CALLS_COUNT}
